name: Run make test

on:
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Run make setup
        run: make setup

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Run make test
        run: make test

